export const Users = [
  {
    _id: 1,
    username: "emu",
    email: "alex@gmail.com",
    profilePicture: "person/1.jpeg",
    coverPicture: "post/1.jpeg",
    desc: "I love nature and books",
    city: "Dhaka",
    from: "Rangamati",
    relationship: "in a relationship",
  },
  {
    _id: 2,
    username: "Mr. White",
    email: "mr.white@gmail.com",
    profilePicture: "person/2.jpeg",
    coverPicture: "post/2.jpeg",
    desc: "Holidays are for coffee and midnight parties",
    city: "Dhaka",
    from: "Barishal",
    relationship: "complicated",
  },
  {
    _id: 3,
    username: "tasnim",
    email: "tasnim@gmail.com",
    profilePicture: "person/3.jpeg",
    coverPicture: "post/3.jpeg",
    desc: "knowledge i power",
    city: "Chittagong",
    from: "Chittagong",
    relationship: "single",
  },
  {
    _id: 4,
    username: "alex",
    email: "alex@gmail.com",
    profilePicture: "person/4.jpeg",
    coverPicture: "post/4.jpeg",
    desc: "Someone's watching us from above",
    city: "New York",
    from: "Rome",
    relationship: "in a relationship",
  },
  {
    _id: 5,
    username: "helen",
    email: "helen@gmail.com",
    profilePicture: "person/5.jpeg",
    coverPicture: "post/5.jpeg",
    desc: "I love nature and books",
    city: "Dhaka",
    from: "Bandarban",
    relationship: "in a relationship",
  },
  {
    _id: 6,
    username: "mulen",
    email: "mulen@gmail.com",
    profilePicture: "person/6.jpeg",
    coverPicture: "post/6.jpeg",
    desc: "I love nature and books",
    city: "Beijing",
    from: "China",
    relationship: "in a relationship",
  },
  {
    _id: 7,
    username: "masu",
    email: "masu@gmail.com",
    profilePicture: "person/7.jpeg",
    coverPicture: "post/7.jpeg",
    desc: "I love drawing",
    city: "Dhaka",
    from: "Italy",
    relationship: "single",
  },
  {
    _id: 8,
    username: "jordan",
    email: "jordan@gmail.com",
    profilePicture: "person/8.jpeg",
    coverPicture: "post/8.jpeg",
    desc: "I love nature and books",
    city: "Dhaka",
    from: "Rangamati",
    relationship: "in a relationship",
  },
];

export const Posts = [
  {
    _id: 1,
    userId: 1,
    desc: "what a beautiful evening",
    img: "post/1.jpeg",
    likes: 43,
    comments: [
      {
        userId: 2,
        post: "this is beatiful",
        likes: 2,
        dislikes: 0,
      },
      {
        userId: 3,
        post: "Im loving this",
        likes: 3,
        dislikes: 2,
      },
    ],
    date: "5 minutes ago",
  },
  {
    _id: 2,
    userId: 2,
    img: "post/2.jpeg",
    likes: 107,
    date: "1 hour ago",
  },
  {
    _id: 3,
    userId: 3,
    desc: "just a casual day",
    img: "post/3.jpeg",
    likes: 55,
    date: "1 day ago",
  },
  {
    _id: 4,
    userId: 4,
    desc: "Loving this",
    img: "post/4.jpeg",
    likes: 18,
    date: "2 days ago",
  },
  {
    _id: 5,
    userId: 5,
    desc: "have you been here?",
    img: "post/5.jpeg",
    likes: 60,
    date: "2 days ago",
  },
  {
    _id: 5,
    userId: 5,
    desc: "what a beautiful evening",
    img: "post/6.jpeg",
    likes: 33,
    date: "55 minutes ago",
  },
];
